/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocalePrivacyRouteImport } from './routes/$locale.privacy'
import { Route as LocaleTermsRouteImport } from './routes/$locale.terms'
import { Route as LocaleVerifyRouteImport } from './routes/$locale.verify'
import { Route as AdminBehaviorRouteImport } from './routes/admin.behavior'
import { Route as ApiExperimentReportRouteImport } from './routes/api.experiment-report'
import { Route as ApiMayaReportRouteImport } from './routes/api.maya-report'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as LocaleRCodeRouteImport } from './routes/$locale.r.$code'
import { Route as ApiCronVerificationReminderRouteImport } from './routes/api.cron.verification-reminder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVerifyRoute = LocaleVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminBehaviorRoute = AdminBehaviorRouteImport.update({
  id: '/admin/behavior',
  path: '/admin/behavior',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExperimentReportRoute = ApiExperimentReportRouteImport.update({
  id: '/api/experiment-report',
  path: '/api/experiment-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMayaReportRoute = ApiMayaReportRouteImport.update({
  id: '/api/maya-report',
  path: '/api/maya-report',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRCodeRoute = LocaleRCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiCronVerificationReminderRoute =
  ApiCronVerificationReminderRouteImport.update({
    id: '/api/cron/verification-reminder',
    path: '/api/cron/verification-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/verify': typeof LocaleVerifyRoute
  '/admin/behavior': typeof AdminBehaviorRoute
  '/api/experiment-report': typeof ApiExperimentReportRoute
  '/api/maya-report': typeof ApiMayaReportRoute
  '/r/$code': typeof RCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/r/$code': typeof LocaleRCodeRoute
  '/api/cron/verification-reminder': typeof ApiCronVerificationReminderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/verify': typeof LocaleVerifyRoute
  '/admin/behavior': typeof AdminBehaviorRoute
  '/api/experiment-report': typeof ApiExperimentReportRoute
  '/api/maya-report': typeof ApiMayaReportRoute
  '/r/$code': typeof RCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/r/$code': typeof LocaleRCodeRoute
  '/api/cron/verification-reminder': typeof ApiCronVerificationReminderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/verify': typeof LocaleVerifyRoute
  '/admin/behavior': typeof AdminBehaviorRoute
  '/api/experiment-report': typeof ApiExperimentReportRoute
  '/api/maya-report': typeof ApiMayaReportRoute
  '/r/$code': typeof RCodeRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/r/$code': typeof LocaleRCodeRoute
  '/api/cron/verification-reminder': typeof ApiCronVerificationReminderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/privacy'
    | '/terms'
    | '/verify'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/verify'
    | '/admin/behavior'
    | '/api/experiment-report'
    | '/api/maya-report'
    | '/r/$code'
    | '/unsubscribe/$token'
    | '/$locale/'
    | '/$locale/r/$code'
    | '/api/cron/verification-reminder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/verify'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/verify'
    | '/admin/behavior'
    | '/api/experiment-report'
    | '/api/maya-report'
    | '/r/$code'
    | '/unsubscribe/$token'
    | '/$locale'
    | '/$locale/r/$code'
    | '/api/cron/verification-reminder'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/privacy'
    | '/terms'
    | '/verify'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/verify'
    | '/admin/behavior'
    | '/api/experiment-report'
    | '/api/maya-report'
    | '/r/$code'
    | '/unsubscribe/$token'
    | '/$locale/'
    | '/$locale/r/$code'
    | '/api/cron/verification-reminder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  AdminBehaviorRoute: typeof AdminBehaviorRoute
  ApiExperimentReportRoute: typeof ApiExperimentReportRoute
  ApiMayaReportRoute: typeof ApiMayaReportRoute
  RCodeRoute: typeof RCodeRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  ApiCronVerificationReminderRoute: typeof ApiCronVerificationReminderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/verify': {
      id: '/$locale/verify'
      path: '/verify'
      fullPath: '/$locale/verify'
      preLoaderRoute: typeof LocaleVerifyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/behavior': {
      id: '/admin/behavior'
      path: '/admin/behavior'
      fullPath: '/admin/behavior'
      preLoaderRoute: typeof AdminBehaviorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experiment-report': {
      id: '/api/experiment-report'
      path: '/api/experiment-report'
      fullPath: '/api/experiment-report'
      preLoaderRoute: typeof ApiExperimentReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maya-report': {
      id: '/api/maya-report'
      path: '/api/maya-report'
      fullPath: '/api/maya-report'
      preLoaderRoute: typeof ApiMayaReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/r/$code': {
      id: '/$locale/r/$code'
      path: '/r/$code'
      fullPath: '/$locale/r/$code'
      preLoaderRoute: typeof LocaleRCodeRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/cron/verification-reminder': {
      id: '/api/cron/verification-reminder'
      path: '/api/cron/verification-reminder'
      fullPath: '/api/cron/verification-reminder'
      preLoaderRoute: typeof ApiCronVerificationReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleRouteChildren {
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleVerifyRoute: typeof LocaleVerifyRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleRCodeRoute: typeof LocaleRCodeRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleVerifyRoute: LocaleVerifyRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleRCodeRoute: LocaleRCodeRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  AdminBehaviorRoute: AdminBehaviorRoute,
  ApiExperimentReportRoute: ApiExperimentReportRoute,
  ApiMayaReportRoute: ApiMayaReportRoute,
  RCodeRoute: RCodeRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  ApiCronVerificationReminderRoute: ApiCronVerificationReminderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
